# -*- coding: utf-8 -*-
"""HistoricalStock.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1usEyRvcoB3Z4-4SifJgpWjVeev7HyoBo
"""

from pandas_datareader.yahoo.actions import YahooDivReader
import math
from IPython.utils.text import get_text_list
from bs4 import BeautifulSoup
import requests
import time
import datetime
import smtplib
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas_datareader import data as pdr

#url = 'https://finance.yahoo.com/quote/SPY/history?period1=728265600&period2=1688688000&interval=1d&filter=history&frequency=1d&includeAdjustedClose=true'

stawk = input("Which ticker do you want history for:")
Yyrr = int(input("Starting which Year(#s only):"))
mnnth = int(input("Starting which Month(#s only):"))
dyy = int(input("Starting which Day(#s only):"))

#SPY started 1993, 1(jan), 22
tickers = []
tickers.append(stawk)
period1 = int(time.mktime(datetime.datetime(Yyrr,mnnth,dyy,23,59).timetuple()))
tdy = datetime.datetime.now()
yr = tdy.year
mnth = tdy.month
dy = tdy.day
period2 = int(time.mktime(datetime.datetime(yr,mnth,dy,23,59).timetuple()))
interval = '1d'
filepath = 'Yahoo'+stawk+'History.csv'
print(filepath)

for ticker in tickers:
  url2 = f'https://query1.finance.yahoo.com/v7/finance/download/{ticker}?period1={period1}&period2={period2}&interval={interval}&events=history&includeAdjustedClose=true'
  df = pd.read_csv(url2)

print(df)

df.to_csv(filepath,index=False)

#Monte Carlo Simulation 1
dt = pd.read_csv('YahooSPYHistory.csv')

mean0 = dt['Close'].mean()
sum0 = dt['Close'].sum()
max0 = dt['Close'].max()
min0 = dt['Close'].min()
count0 = dt['Close'].count()
median0 = dt['Close'].median()
std1 = dt['Close'].std()
var1 = dt['Close'].var()



mn = mean0
sd = std1
vl = count0

x = np.random.normal(mn,sd,vl)

plt.hist(x,100)
plt.show()